/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Property = IDL.Record({
  'title' : IDL.Text,
  'propertyType' : IDL.Text,
  'bedrooms' : IDL.Nat,
  'area' : IDL.Nat,
  'description' : IDL.Text,
  'bathrooms' : IDL.Nat,
  'price' : IDL.Nat,
  'location' : IDL.Text,
});
export const Time = IDL.Int;
export const ContactEntry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProperty' : IDL.Func([Property], [], []),
  'getAllContactEntries' : IDL.Func([], [IDL.Vec(ContactEntry)], ['query']),
  'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getProperty' : IDL.Func([IDL.Text], [IDL.Opt(Property)], ['query']),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Property = IDL.Record({
    'title' : IDL.Text,
    'propertyType' : IDL.Text,
    'bedrooms' : IDL.Nat,
    'area' : IDL.Nat,
    'description' : IDL.Text,
    'bathrooms' : IDL.Nat,
    'price' : IDL.Nat,
    'location' : IDL.Text,
  });
  const Time = IDL.Int;
  const ContactEntry = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addProperty' : IDL.Func([Property], [], []),
    'getAllContactEntries' : IDL.Func([], [IDL.Vec(ContactEntry)], ['query']),
    'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getProperty' : IDL.Func([IDL.Text], [IDL.Opt(Property)], ['query']),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };